services:

  # --- SERVICIO BACKEND ---
  backend:
    build: ./backend 
    env_file:
    - .env
    container_name: pharmacy_backend 
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pharmacy_db
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/pharmacy_db
    depends_on:
      - db
    restart: always

  # --- SERVICIO BASE DE DATOS ---
  db:
    image: postgres:16
    container_name: pharmacy_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pharmacy_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    container_name: pharmacy_frontend
    ports:
      - "8081:8081"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=localhost
    depends_on:
      - backend

volumes:
  postgres_data: