/**
 * Datos de prueba para visualizar la interfaz sin depender del backend.
 * Activa DEMO_MODE en src/config/constants.ts para usar estos mocks.
 */

import {User, UserRole, Product, Sale, PaymentMethod} from '../models';

export const mockUser: User = {
  id: 1,
  email: 'demo@sisdrog.com',
  fullName: 'Usuario Demo',
  role: UserRole.ADMIN,
  isActive: true,
};

export const mockProducts: Product[] = [
  {
    id: 1,
    code: 'MED-001',
    name: 'Paracetamol 500mg',
    description: 'Analgésico y antipirético',
    laboratory: 'Lab. Genéricos SA',
    presentation: 'Tabletas',
    stock: 124,
    minStock: 20,
    salePrice: 4.5,
    category: 'Analgésicos',
    purchasePrice: 2800,
    expirationDate: '2026-12-01',
    iva: 19,
    isActive: true,
  },
  {
    id: 2,
    code: 'MED-002',
    name: 'Amoxicilina 875mg',
    description: 'Antibiótico de amplio espectro',
    laboratory: 'Bayer',
    presentation: 'Tabletas',
    stock: 12,
    minStock: 10,
    salePrice: 12.0,
    category: 'Antibióticos',
    purchasePrice: 3100,
    expirationDate: '2026-10-15',
    iva: 19,
    isActive: true,
  },
  {
    id: 3,
    code: 'MED-003',
    name: 'Ibuprofeno 400mg',
    description: 'Antiinflamatorio no esteroideo',
    laboratory: 'Pfizer',
    presentation: 'Tabletas',
    stock: 85,
    minStock: 15,
    salePrice: 6.75,
    category: 'Analgésicos',
    purchasePrice: 3100,
    expirationDate: '2026-10-15',
    iva: 19,
    isActive: true,
  },
  {
    id: 4,
    code: 'MED-004',
    name: 'Aspirina 100mg',
    description: 'Analgésico y antiinflamatorio',
    laboratory: 'Bayer',
    presentation: 'Tabletas',
    stock: 0,
    minStock: 10,
    salePrice: 3.2,
    category: 'Analgésicos',
    purchasePrice: 5400,
    expirationDate: '2026-08-20',
    iva: 19,
    isActive: true,
  },
  {
    id: 5,
    code: 'MED-005',
    name: 'Vitamina C 1g',
    description: 'Suplemento vitamínico',
    laboratory: 'Redoxon',
    presentation: 'Tabletas efervescentes',
    stock: 43,
    minStock: 12,
    salePrice: 8.9,
    category: 'Vitaminas',
    purchasePrice: 3900,
    expirationDate: '2026-11-10',
    iva: 19,
    isActive: true,
  },
  {
    id: 6,
    code: 'MED-006',
    name: 'Omeprazol 20mg x14',
    description: 'Protector gástrico',
    laboratory: 'Genfar',
    presentation: 'Cápsulas',
    stock: 60,
    minStock: 10,
    salePrice: 8.9,
    category: 'Cuidado Personal',
    purchasePrice: 5400,
    expirationDate: '2026-08-20',
    iva: 19,
    isActive: true,
  },
];

export const mockSales: Sale[] = [
  {
    id: 1,
    invoiceNumber: 'FAC-0001',
    customerDocument: '1234567890',
    customerName: 'Juan Pérez',
    items: [
      {
        id: 1,
        productId: 1,
        productName: 'Paracetamol 500mg x10',
        quantity: 2,
        unitPrice: 4500,
        subtotal: 9000,
      },
    ],
    subtotal: 9000,
    tax: 1710,
    total: 10710,
    paymentMethod: PaymentMethod.CASH,
    soldBy: 'Usuario Demo',
  },
  {
    id: 2,
    invoiceNumber: 'FAC-0002',
    customerDocument: '0987654321',
    customerName: 'María García',
    items: [
      {
        id: 2,
        productId: 2,
        productName: 'Ibuprofeno 400mg x10',
        quantity: 1,
        unitPrice: 5200,
        subtotal: 5200,
      },
      {
        id: 3,
        productId: 3,
        productName: 'Loratadina 10mg x10',
        quantity: 1,
        unitPrice: 3800,
        subtotal: 3800,
      },
    ],
    subtotal: 9000,
    tax: 1710,
    total: 10710,
    paymentMethod: PaymentMethod.CARD,
    soldBy: 'Usuario Demo',
  },
];
