/**
 * Datos de prueba para visualizar la interfaz sin depender del backend.
 * Activa DEMO_MODE en src/config/constants.ts para usar estos mocks.
 */

import {User, UserRole, Product, Sale, PaymentMethod, InventoryAlertsResponse} from '../models';

export const mockUser: User = {
  id: 1,
  email: 'demo@sisdrog.com',
  fullName: 'Usuario Demo',
  role: UserRole.ADMIN,
  isActive: true,
};

export const mockProducts: Product[] = [
  {
    id: 14,
    code: 'MED-001',
    name: 'Paracetamol 500mg',
    description: 'Analgésico y antipirético',
    laboratory: 'Lab. Genfar',
    presentation: 'Tabletas',
    stock: 245,
    minStock: 20,
    salePrice: 4.5,
    category: 'Analgésicos',
    purchasePrice: 2800,
    expirationDate: '2025-08-15',
    iva: 19,
    isActive: true,
    origin: 'Compra',
  },
  {
    id: 89,
    code: 'MED-002',
    name: 'Amoxicilina 875mg',
    description: 'Antibiótico de amplio espectro',
    laboratory: 'Lab. Pfizer',
    presentation: 'Tabletas',
    stock: 12,
    minStock: 15,
    salePrice: 0,
    category: 'Antibióticos',
    purchasePrice: 3100,
    expirationDate: '2024-02-11',
    iva: 19,
    isActive: true,
    origin: 'Donación',
  },
  {
    id: 102,
    code: 'MED-003',
    name: 'Vitamina C 1000mg',
    description: 'Suplemento vitamínico',
    laboratory: 'Lab. Bayer',
    presentation: 'Tabletas efervescentes',
    stock: 0,
    minStock: 15,
    salePrice: 8.75,
    category: 'Vitaminas',
    purchasePrice: 3900,
    expirationDate: '2026-05-20',
    iva: 19,
    isActive: true,
    origin: 'Compra',
  },
  {
    id: 45,
    code: 'MED-004',
    name: 'Ibuprofeno 400mg',
    description: 'Antiinflamatorio no esteroideo',
    laboratory: 'Lab. MK',
    presentation: 'Tabletas',
    stock: 150,
    minStock: 20,
    salePrice: 3.2,
    category: 'Analgésicos',
    purchasePrice: 1800,
    expirationDate: '2024-12-10',
    iva: 19,
    isActive: true,
    origin: 'Compra',
  },
  {
    id: 31,
    code: 'MED-005',
    name: 'Loratadina 10mg',
    description: 'Antihistamínico',
    laboratory: 'Lab. Tecnoquímicas',
    presentation: 'Tabletas',
    stock: 75,
    minStock: 10,
    salePrice: 2.8,
    category: 'Alérgicos',
    purchasePrice: 1200,
    expirationDate: '2026-03-22',
    iva: 19,
    isActive: true,
    origin: 'Compra',
  },
  {
    id: 67,
    code: 'MED-006',
    name: 'Omeprazol 20mg',
    description: 'Protector gástrico',
    laboratory: 'Lab. Genfar',
    presentation: 'Cápsulas',
    stock: 60,
    minStock: 10,
    salePrice: 5.4,
    category: 'Gástrico',
    purchasePrice: 2100,
    expirationDate: '2026-07-18',
    iva: 19,
    isActive: true,
    origin: 'Donación',
  },
  {
    id: 53,
    code: 'MED-007',
    name: 'Metformina 850mg',
    description: 'Antidiabético oral',
    laboratory: 'Lab. Lafrancol',
    presentation: 'Tabletas',
    stock: 8,
    minStock: 20,
    salePrice: 6.9,
    category: 'Diabetes',
    purchasePrice: 3200,
    expirationDate: '2025-11-05',
    iva: 19,
    isActive: true,
    origin: 'Compra',
  },
  {
    id: 78,
    code: 'MED-008',
    name: 'Atorvastatina 40mg',
    description: 'Reductor de colesterol',
    laboratory: 'Lab. Pfizer',
    presentation: 'Tabletas',
    stock: 33,
    minStock: 10,
    salePrice: 12.5,
    category: 'Cardiovascular',
    purchasePrice: 5800,
    expirationDate: '2026-09-30',
    iva: 19,
    isActive: true,
    origin: 'Compra',
  },
  {
    id: 92,
    code: 'MED-009',
    name: 'Diclofenac 75mg',
    description: 'Antiinflamatorio inyectable',
    laboratory: 'Lab. Chalver',
    presentation: 'Ampolla',
    stock: 0,
    minStock: 5,
    salePrice: 4.2,
    category: 'Analgésicos',
    purchasePrice: 1900,
    expirationDate: '2025-06-14',
    iva: 19,
    isActive: true,
    origin: 'Compra',
  },
  {
    id: 115,
    code: 'MED-010',
    name: 'Salbutamol Inhalador',
    description: 'Broncodilatador para asma',
    laboratory: 'Lab. GSK',
    presentation: 'Aerosol',
    stock: 18,
    minStock: 8,
    salePrice: 22.0,
    category: 'Respiratorio',
    purchasePrice: 9500,
    expirationDate: '2026-01-28',
    iva: 19,
    isActive: true,
    origin: 'Compra',
  },
];

export const mockSales: Sale[] = [
  {
    id: 1,
    invoiceNumber: 'FAC-0001',
    customerDocument: '1234567890',
    customerName: 'Juan Pérez',
    items: [
      {
        id: 1,
        productId: 1,
        productName: 'Paracetamol 500mg x10',
        quantity: 2,
        unitPrice: 4500,
        subtotal: 9000,
      },
    ],
    subtotal: 9000,
    tax: 1710,
    total: 10710,
    paymentMethod: PaymentMethod.CASH,
    soldBy: 'Usuario Demo',
  },
  {
    id: 2,
    invoiceNumber: 'FAC-0002',
    customerDocument: '0987654321',
    customerName: 'María García',
    items: [
      {
        id: 2,
        productId: 2,
        productName: 'Ibuprofeno 400mg x10',
        quantity: 1,
        unitPrice: 5200,
        subtotal: 5200,
      },
      {
        id: 3,
        productId: 3,
        productName: 'Loratadina 10mg x10',
        quantity: 1,
        unitPrice: 3800,
        subtotal: 3800,
      },
    ],
    subtotal: 9000,
    tax: 1710,
    total: 10710,
    paymentMethod: PaymentMethod.CARD,
    soldBy: 'Usuario Demo',
  },
];

/** HU-07: datos mock de alertas de inventario. */
export const mockAlerts: InventoryAlertsResponse = {
  lowStock: [
    // Aspirina — agotada (stock 0, minStock 10)
    mockProducts[3],
    // Amoxicilina — stock bajo (stock 12, minStock 10) – ajustamos para demo
    {
      ...mockProducts[1],
      stock: 8,
    },
  ],
  expiringSoon: [
    // Aspirina — vence 2026-08-20
    mockProducts[3],
    // Ibuprofeno — vence 2026-10-15 (dentro de ~3.5 meses)
    mockProducts[2],
    // Amoxicilina — vence 2026-10-15
    mockProducts[1],
  ],
};
