version: '3.8'
services:
  db:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sisdrog
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/sisdrog
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ../frontend
    ports:
      - "3000:80"
    restart: unless-stopped

volumes:
  db-data:
