"""create donations and product movements tables

Revision ID: 5e11b46d9171
Revises: 0dfa7cb93da6
Create Date: 2026-07-03 16:22:12.516483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e11b46d9171'
down_revision: Union[str, Sequence[str], None] = '0dfa7cb93da6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donation_type', sa.String(length=20), nullable=False),
    sa.Column('donor_or_recipient', sa.String(length=200), nullable=True),
    sa.Column('donation_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donations_id'), 'donations', ['id'], unique=False)
    op.create_table('donation_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donation_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donation_items_donation_id'), 'donation_items', ['donation_id'], unique=False)
    op.create_index(op.f('ix_donation_items_id'), 'donation_items', ['id'], unique=False)
    op.create_index(op.f('ix_donation_items_product_id'), 'donation_items', ['product_id'], unique=False)
    op.create_table('product_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('reference_type', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('movement_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_movements_id'), 'product_movements', ['id'], unique=False)
    op.create_index(op.f('ix_product_movements_product_id'), 'product_movements', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_movements_product_id'), table_name='product_movements')
    op.drop_index(op.f('ix_product_movements_id'), table_name='product_movements')
    op.drop_table('product_movements')
    op.drop_index(op.f('ix_donation_items_product_id'), table_name='donation_items')
    op.drop_index(op.f('ix_donation_items_id'), table_name='donation_items')
    op.drop_index(op.f('ix_donation_items_donation_id'), table_name='donation_items')
    op.drop_table('donation_items')
    op.drop_index(op.f('ix_donations_id'), table_name='donations')
    op.drop_table('donations')
    # ### end Alembic commands ###
