"""add product lots and supplier fields

Revision ID: 8814a5aa63c0
Revises: 5e11b46d9171
Create Date: 2026-07-07 20:26:22.938339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8814a5aa63c0'
down_revision: Union[str, Sequence[str], None] = '5e11b46d9171'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Crear tabla product_lots
    op.create_table('product_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('lot_number', sa.String(length=100), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_lots_id'), 'product_lots', ['id'], unique=False)
    op.create_index(op.f('ix_product_lots_product_id'), 'product_lots', ['product_id'], unique=False)

    # 2. Primero quitar FKs que apuntan a suppliers ANTES de borrar suppliers
    op.drop_constraint('products_supplier_id_fkey', 'products', type_='foreignkey')
    op.drop_constraint('purchases_supplier_id_fkey', 'purchases', type_='foreignkey')

    # 3. Ahora sí borrar suppliers (ya no tiene dependencias)
    op.drop_index(op.f('ix_suppliers_id'), table_name='suppliers')
    op.drop_table('suppliers')

    # 4. Borrar purchase_items
    op.drop_index(op.f('ix_purchase_items_id'), table_name='purchase_items')
    op.drop_index(op.f('ix_purchase_items_product_id'), table_name='purchase_items')
    op.drop_index(op.f('ix_purchase_items_purchase_id'), table_name='purchase_items')
    op.drop_table('purchase_items')

    # 5. Agregar columnas nuevas a products
    op.add_column('products', sa.Column('gramaje', sa.String(), nullable=True))
    op.add_column('products', sa.Column('supplier_name', sa.String(length=200), nullable=True))
    op.add_column('products', sa.Column('contact_name', sa.String(length=200), nullable=True))
    op.add_column('products', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('products', sa.Column('address', sa.String(length=300), nullable=True))

    # 6. Quitar columnas obsoletas de products
    op.drop_column('products', 'supplier_id')
    op.drop_column('products', 'expiry_date')
    op.drop_column('products', 'batch')

    # 7. Actualizar purchases — agregar nullable primero por datos existentes
    op.add_column('purchases', sa.Column('product_id', sa.Integer(), nullable=True))
    op.add_column('purchases', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('purchases', sa.Column('unit_price', sa.Float(), nullable=True))
    op.add_column('purchases', sa.Column('lot_number', sa.String(), nullable=True))
    op.drop_index(op.f('ix_purchases_supplier_id'), table_name='purchases')
    op.create_index(op.f('ix_purchases_product_id'), 'purchases', ['product_id'], unique=False)
    op.create_foreign_key(None, 'purchases', 'products', ['product_id'], ['id'])
    op.drop_column('purchases', 'supplier_id')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.create_foreign_key(op.f('purchases_supplier_id_fkey'), 'purchases', 'suppliers', ['supplier_id'], ['id'])
    op.drop_index(op.f('ix_purchases_product_id'), table_name='purchases')
    op.create_index(op.f('ix_purchases_supplier_id'), 'purchases', ['supplier_id'], unique=False)
    op.drop_column('purchases', 'lot_number')
    op.drop_column('purchases', 'unit_price')
    op.drop_column('purchases', 'quantity')
    op.drop_column('purchases', 'product_id')
    op.add_column('products', sa.Column('batch', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('expiry_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('products_supplier_id_fkey'), 'products', 'suppliers', ['supplier_id'], ['id'])
    op.drop_column('products', 'address')
    op.drop_column('products', 'phone')
    op.drop_column('products', 'contact_name')
    op.drop_column('products', 'supplier_name')
    op.drop_column('products', 'gramaje')
    op.create_table('purchase_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('purchase_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('subtotal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('purchase_items_product_id_fkey')),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], name=op.f('purchase_items_purchase_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('purchase_items_pkey'))
    )
    op.create_index(op.f('ix_purchase_items_purchase_id'), 'purchase_items', ['purchase_id'], unique=False)
    op.create_index(op.f('ix_purchase_items_product_id'), 'purchase_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_purchase_items_id'), 'purchase_items', ['id'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('contact', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('suppliers_pkey'))
    )
    op.create_index(op.f('ix_suppliers_id'), 'suppliers', ['id'], unique=False)
    op.drop_index(op.f('ix_product_lots_product_id'), table_name='product_lots')
    op.drop_index(op.f('ix_product_lots_id'), table_name='product_lots')
    op.drop_table('product_lots')
    # ### end Alembic commands ###
