"""remove_unique_constraint_from_product_code

Revision ID: dc83a27c8804
Revises: 8814a5aa63c0
Create Date: 2026-07-10 22:41:29.166956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc83a27c8804'
down_revision: Union[str, Sequence[str], None] = '8814a5aa63c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('products_code_key'), 'products', type_='unique')
    op.drop_index(op.f('ix_products_code'), table_name='products')
    op.create_index(op.f('ix_products_code'), 'products', ['code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_code'), table_name='products')
    op.create_index(op.f('ix_products_code'), 'products', ['code'], unique=True)
    op.create_unique_constraint(op.f('products_code_key'), 'products', ['code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
